name: tinyproxy-ogra
version: "1.8.3"
summary: A very tiny proxy server
description: |
    A small http proxy with the ability to manage url black/white lists.
    .
    Configuration can be done via the snap set/get commands, for supported
    options and examples please see the README.md at
    https://github.com/ogra1/tinyproxy-snap/blob/master/README.md

confinement: strict
grade: stable

apps:
  tinyproxy:
    command: usr/sbin/tinyproxy -d -c ${SNAP_DATA}/tinyproxy.conf
    daemon: simple
    plugs: [network, network-bind]

parts:
  tinyproxy:
    source: .
    plugin: dump
    stage-packages: [tinyproxy]
