name: tinyproxy-ogra
version: "1.8.3"
summary: very tiny proxy server
description: a small http proxy with the ability to manage url black/white lists
confinement: strict
grade: stable

apps:
  tinyproxy:
    command: ./launcher.sh
    daemon: simple
    plugs: [network, network-bind]

parts:
  tinyproxy:
    source: .
    plugin: dump
    stage-packages: [tinyproxy]
